# Generated by Django 6.0.1 on 2026-03-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('menusAndRecipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='linked_menu_item',
            field=models.ForeignKey(blank=True, help_text='Link to menu item for Prepared Items category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='menusAndRecipes.menuitem'),
        ),
    ]
