# Generated by Django 6.0.1 on 2026-03-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_linked_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
