# Generated by Django 6.0.1 on 2026-03-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_current_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('branch_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(max_length=200)),
                ('menu_item_sku', models.CharField(max_length=50)),
                ('units_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity_deducted', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('inventory_matched', models.BooleanField(default=False)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_entries', to='inventory.inventoryitem')),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_entries', to='inventory.consumptionentry')),
            ],
            options={
                'ordering': ['menu_item_sku', 'ingredient_name'],
            },
        ),
    ]
