# Generated by Django 6.0.1 on 2026-03-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0004_consumptionentry_bomentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches where this item is available', related_name='available_inventory_items', to='branches.branch'),
        ),
    ]
