# Generated by Django 6.0.1 on 2026-03-22 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0006_stocktransfer'),
        ('menusAndRecipes', '0002_alter_recipe_unique_together_recipe_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptionentry',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='min_stock_level',
        ),
        migrations.AddField(
            model_name='consumptionentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_entries', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum quantity before a low-stock alert is raised for this branch', max_digits=10),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='linked_menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='menusAndRecipes.menuitem'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
