# Generated by Django 6.0.1 on 2026-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_consumptionentry_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UomPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. "Kilogram", "Piece"', max_length=50, unique=True)),
                ('abbreviation', models.CharField(blank=True, default='', help_text='E.g. "kg", "pcs"', max_length=10)),
            ],
            options={
                'verbose_name': 'Unit of Measurement',
                'verbose_name_plural': 'Units of Measurement',
                'ordering': ['name'],
            },
        ),
    ]
