# Generated by Django 6.0.1 on 2026-03-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_decouple_from_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-received_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, default='', help_text='E.g. "Meat Supplier", "Fresh Produce", "Beverages"', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive instead of deleting to preserve purchase history'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Typical delivery lead time in days'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, default='', help_text='E.g. "COD", "Net 15 Days"', max_length=100),
        ),
    ]
