# Generated by Django 6.0.1 on 2026-01-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch_type', models.CharField(choices=[('kitchen', 'Full-Service Restaurant'), ('cafe_only', 'Resto Café (No Cooking)')], max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
